services:
  - type: web
    name: tiktok-live-recorder
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      apt-get update
      apt-get install -y ffmpeg
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        fromService:
          type: web
          name: tiktok-live-recorder
          property: port
    disk:
      name: recordings-disk
      mountPath: /opt/render/project/src/recordings
      sizeGB: 1
