services:
  - type: web
    name: tiktok-livestream-recorder
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py main:app
    envVars:
      - key: PORT
        sync: false
      - key: PYTHON_VERSION
        value: 3.13.4
    healthCheckPath: /health
    scaling:
      minInstances: 1
      maxInstances: 1
