services:
  - type: web
    name: tiktok-livestream-recorder
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -c "import os; from main import app; app.run(host='0.0.0.0', port=int(os.environ.get('PORT', 10000)))"
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.13.4
    scaling:
      minInstances: 1
      maxInstances: 1
