services:
  - type: web
    name: tiktok-livestream-recorder
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: PORT
        value: 10000
    scaling:
      minInstances: 1
      maxInstances: 1
    scaling:
      minInstances: 1
      maxInstances: 1
